# Will override root ncurc.yml
# @link https://github.com/raineorshine/npm-check-updates

reject: [
    # Ignore package direct deps for npm-check-updates. That way we declare a less
    # restrictive range if the consuming app lock its deps to exact versions
    '@tsed/exceptions',
    'dequal',
  ]
